{"trial_id": "0022", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "hidden_layer_activation", "default": "_cart_relu", "conditions": [], "values": ["_cart_relu", "_complex_cardioid"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "output_layer_activation", "default": "_sigmoid_real", "conditions": [], "values": ["_sigmoid_real", "_softmax_real_with_abs", "_softmax_real_with_avg", "_softmax_real_with_mult", "_softmax_of_softmax_real_with_mult", "_softmax_of_softmax_real_with_avg", "_convert_to_real_with_abs", "_softmax_real_with_polar"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0001], "ordered": true}}, {"class_name": "Choice", "config": {"name": "optimizer", "default": "adam", "conditions": [], "values": ["adam", "sgd"], "ordered": false}}], "values": {"hidden_layer_activation": "_complex_cardioid", "output_layer_activation": "_sigmoid_real", "learning_rate": 0.01, "optimizer": "adam", "tuner/epochs": 15, "tuner/initial_epoch": 0, "tuner/bracket": 0, "tuner/round": 0}}, "metrics": {"metrics": {"loss": {"direction": "min", "observations": [{"value": [0.16156157851219177], "step": 14}]}, "accuracy": {"direction": "max", "observations": [{"value": [0.9857000112533569], "step": 14}]}, "val_loss": {"direction": "min", "observations": [{"value": [0.9812236428260803], "step": 14}]}, "val_accuracy": {"direction": "max", "observations": [{"value": [0.9632999897003174], "step": 14}]}}}, "score": 0.9632999897003174, "best_step": 14, "status": "COMPLETED", "message": "Traceback (most recent call last):\n  File \"/home/panda/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 270, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/panda/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 235, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/panda/.local/lib/python3.10/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/panda/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/home/panda/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/home/panda/.local/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 144, in fit\n    return model.fit(*args, **kwargs)\n  File \"/home/panda/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/panda/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner_utils.py\", line 172, in on_epoch_end\n    self._save_model()\n  File \"/home/panda/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner_utils.py\", line 182, in _save_model\n    self.model.save_weights(write_filepath)\ntensorflow.python.framework.errors_impl.PermissionDeniedError: {{function_node __wrapped__MergeV2Checkpoints_device_/job:localhost/replica:0/task:0/device:CPU:0}} keras_tuner/cvnn_mnist/trial_0022/checkpoint.index; Permission denied [Op:MergeV2Checkpoints]\n"}